apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sys-log-collector
  namespace: logs-collector-ns
  labels:
    k8s-app: sys-logger
spec:
  selector:
    matchLabels:
      name: sys-log-collector
  template:
    metadata:
      labels:
        name: sys-log-collector
    spec:
      containers:
      - name: sys-log-collector-contianer
        image: ani007s/up-local:32
        env:
          - name: ROLE_ARN
            valueFrom:
              configMapKeyRef:
                name: bucket-details
                key: ROLE_ARN
          - name: AWS_S3_BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                name: bucket-details
                key: BUCKET_NAME
          - name: AWS_DEFAULT_REGION
            valueFrom:
              configMapKeyRef:
                name: bucket-details
                key: BUCKET_REGION
          - name: AWS_S3_BUCKET_REGION
            valueFrom:
              configMapKeyRef:
                name: bucket-details
                key: BUCKET_REGION
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: username
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
        - name: system-logs
          mountPath: /var/log
        - name: bucket-details
          mountPath: /config
      volumes:
      - name: bucket-details
        configMap:
          name: bucket-details
      - name: system-logs
        hostPath:
          path: /var/log
      - name: mysecret
        secret:
          secretName: mysecret
